version: '3'
 
volumes:
  datafiles:
 
services:
  db:
    image: mysql:8.0.0
    volumes:
      - datafiles:/var/lib/mysql
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_TCP_PORT: 3306
 
  mvc:
    build:
      context: .
      dockerfile: Dockerfile.mvc
    depends_on:
      - db
    ports:
      - "5000:80"
      - "5001:443"
    #restart: always
    environment:
      - DBHOST=db
      - DBPORT=3306
      - DBPASSWORD=secret
      - ASPNETCORE_ENVIRONMENT=Development
