// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SchoolApi.Data.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20201102072408_M1")]
    partial class M1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BCITID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Set")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = "ec6ca32f-e5ad-40a3-b236-8e8fa73eb03e",
                            BCITID = "A00123448",
                            City = "Chilliwack",
                            Email = "jim@potter.com",
                            FirstName = "Jim",
                            LastName = "Potter",
                            MobileNo = "604-123-4567",
                            Option = "Web & Mobile",
                            Set = "S"
                        },
                        new
                        {
                            StudentId = "b80e193c-748e-4ff9-ac73-eac79f19a10c",
                            BCITID = "A00816734",
                            City = "Capillano",
                            Email = "will@smith.com",
                            FirstName = "Will",
                            LastName = "Smith",
                            MobileNo = "604-111-1111",
                            Option = "Mechatronics",
                            Set = "V"
                        },
                        new
                        {
                            StudentId = "71d30492-e04a-4f88-8ab4-8d197c49bde5",
                            BCITID = "A00648317",
                            City = "Victoria",
                            Email = "tim@james.com",
                            FirstName = "Tim",
                            LastName = "James",
                            MobileNo = "604-222-2222",
                            Option = "Mechatronics",
                            Set = "v"
                        },
                        new
                        {
                            StudentId = "9ce3572e-3898-4736-8fe8-069c7eefb630",
                            BCITID = "A00123451",
                            City = "Mission",
                            Email = "sarah@parker.com",
                            FirstName = "Sarah",
                            LastName = "Parker",
                            MobileNo = "604-333-3333",
                            Option = "Web & Mobile",
                            Set = "S"
                        },
                        new
                        {
                            StudentId = "7e780f84-6090-43ba-bc6c-850d8e771795",
                            BCITID = "A00123452",
                            City = "Vancouver",
                            Email = "ricky@low.com",
                            FirstName = "Ricky",
                            LastName = "Low",
                            MobileNo = "604-444-4444",
                            Option = "AI",
                            Set = "F"
                        },
                        new
                        {
                            StudentId = "72e22b35-29e0-4707-8b02-84a3b39f0e86",
                            BCITID = "A00123453",
                            City = "Burnaby",
                            Email = "terry@crews.com",
                            FirstName = "Terry",
                            LastName = "Crews",
                            MobileNo = "604-555-5555",
                            Option = "AI",
                            Set = "F"
                        },
                        new
                        {
                            StudentId = "709208d3-a4f1-492d-9138-e51d4fb66ed2",
                            BCITID = "A00123454",
                            City = "Los Angeles",
                            Email = "jerry@wither.com",
                            FirstName = "Jerry",
                            LastName = "Wither",
                            MobileNo = "604-666-6666",
                            Option = "Web & Mobile",
                            Set = "S"
                        },
                        new
                        {
                            StudentId = "4cedf42d-8371-408a-8f24-e2d32c974416",
                            BCITID = "A00123455",
                            City = "Langley",
                            Email = "jones@potter.com",
                            FirstName = "Jones",
                            LastName = "Potter",
                            MobileNo = "604-777-7777",
                            Option = "Web & Mobile",
                            Set = "S"
                        },
                        new
                        {
                            StudentId = "d313f82a-781e-44e3-948f-e6e488112bc8",
                            BCITID = "A00123456",
                            City = "Surrey",
                            Email = "Lana@DelRay.com",
                            FirstName = "Lana",
                            LastName = "DelRay",
                            MobileNo = "604-888-8888",
                            Option = "Tech Entrepeneur",
                            Set = "G"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
